# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ff75a6bb340ad42192a8857a9147f51923e74df596b0692b32973eb1fa4957d43e7645cc0da55ff33bf2421f7d1f8e1d6a3c6c7ea7386fbfc92a6e86079468c

test:
  secret_key_base: 05fbf8f44c86d4765d68d185476450c610224815c77c0644b4e9a9957199d87c879b5c18b40499135e925adb7f013e71056d7e6aeb24e68f52ccb2120476fb89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
